### ISSUE TITLE
responsive nav bar

### ISSUE THREAD

**Issue by JulienLiboureau** [aeteseb/aetesis_frappe_customizations#45]
- [x] - BURGER MENU : 
- [x] - fix layout, burger icone and cart icone have to stay immobile
- [x] - il faut que les textes passent à droite des icones
- [x] - le tout en liste verticale
- [x] - ou sinon une colonne de 3 et une colonne de 2 
- [x] - Prévoir que l'icone pays reste bien à côté de la search bar. (attention à toutes les tailles de device)

**Comment by aeteseb** [comment]
- [ ] nav xxl
